language: php

php:
 - 5.6
 - 7.0
 - 7.1
 - 7.2

env:
  matrix:
  - PREFER_LOWEST=""
  - PREFER_LOWEST="--prefer-lowest"

before_script:
 - composer update --no-interaction $PREFER_LOWEST

script:
 - vendor/bin/phpunit

after_script:
 - php vendor/bin/coveralls -v
